extends RefCounted
## Campaign nav grid (state format 6). GENERATED by tools/campaign_grid.gd
## from game/campaign/map_geo.gd: do not edit by hand; regenerate.
## ROWS: one string per row, one character per cell: "." sea, ","
## unclaimed land (impassable), "A"-"Z" regions 0-25, "a"-"z" 26-51 (CData
## REGIONS order). SITE / PORT / CAMP: per region the cell index (y * W + x)
## of its settlement, its port (-1 none) and a field cell away from the
## settlement. OVERRIDES: [cell, cost] pairs (roads, fords: later).

const CELL_PX := 20
const W := 138
const H := 70
const SITE: Array[int] = [3538, 2431, 4096, 3960, 4522, 6172, 1041, 1051, 6436, 6860, 5319, 3388, 7192, 6384, 5007, 3364, 3480, 4854, 5663, 2492, 2544, 2673, 880, 1024, 4404, 5094, 5502, 3426, 5919, 6341, 6337, 6888, 6979, 7670, 7379, 7746]
const PORT: Array[int] = [3537, 2019, -1, -1, 4384, 6034, -1, -1, 6298, 6722, 5318, 3250, 7054, 6383, -1, 3226, -1, -1, -1, -1, 2543, -1, -1, -1, -1, -1, 5501, 3425, 5918, -1, 6199, -1, 6978, -1, 7101, 7608]
const CAMP: Array[int] = [3125, 2428, 3681, 3963, 4657, 5760, 1454, 1466, 6439, 6444, 4766, 3247, 6642, 6242, 4591, 3497, 3065, 4989, 5391, 3048, 2132, 2394, 877, 1027, 3990, 5229, 5087, 3147, 5784, 5925, 5923, 6885, 7114, 7943, 7514, 8026]
const OVERRIDES: Array[int] = []
const ROWS: Array[String] = [
	"................................,,,,,,,,,,,,,,WWWWWWWWWWXXXXX,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,",
	"................................,,,,,,,,,,,,,,WWWWWWWWWWXXXXX,,,,,,,,,,,,GG,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,",
	".................................,,,,,,,,,,,,,WWWWWWWWWWXXXXXX,,,,,,,,,,GGGG,,,,,,,,,HH,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,",
	"...................................,,,,,,,,,,,WWWWWWWWWWXXXXXXX,,,,,,,,,GGGGG,,,,,,,HHHH,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,",
	"...................................,,,,,,,,,,,WWWWWWWWWWXXXXXXX,,,,,,,,GGGGGGG,,,,,HHHHHH,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,",
	"....................................,,,,,,,,,,WWWWWWWWWWXXXXXXXX,,,,,,GGGGGGGGG,,,HHHHHHHH,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,",
	"....................................,,,,,,,,,,WWWWWWWWWWXXXXXXXXX,,,,,GGGGGGGGGGGHHHHHHHHHH,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,",
	"....................................,,,,,,,,,,WWWWWWWWWXXXXXXXXXX,,,,GGGGGGGGGGGGHHHHHHHHHH..,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,",
	"...................................,,,,,,,,,,,WWWWWWWWWXXXXXXXXXXX,,GGGGGGGGGGGGGHHHHHHHH....,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,",
	"...................................,,,,,,,,,,,WWWWWWWWWXXXXXXXXXXXXGGGGGGGGGGGGGGHHHHHHHHHH..,,.,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,",
	"...................................,,,,,,,,,,,WWWWWWWWWXXXXXXXXXXXXGGGGGGGGGGGGGHHHHHHHH..HH.,..,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,",
	"...................................,,,,,,,,,,,WWWWWWWWWXXXXXXXXXXXXGGGGGGGGGGGGGHHHHHHHH...HHH...,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,",
	"...................................,,,,,,,,,,,WWWWWWWWWXXXXXXXUUUUUUGGGGGGGGGGGGHHHHHHHH.....HHH.,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,",
	"...................................,,,,,,,,,,VVVVVVVVVVVXUUUUUUUUUUUGGGGGG.GGGGGBBBBBBBB.......HHH,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,",
	"...................................,,,,,,,,,,VVVVVVVVVVVUUUUUUUUUUUUUGGG.....GGBBBBBBBBBB........HH,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,",
	"..................................,,,,,,,,,,VVVVVVVVVVVVUUUUUUUUUUUUUUG.......BBBBBBBBBBBB........HHb,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,",
	".........TTTTTT...................,,,,,,,,,,VVVVVVVVVVVVUUUUUUUUUUUUU..........BBBBBBBBBBBBB........bbb,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,",
	"........TTTTTTTTTTTTTQQQQQ........,,,,,,,,,,VVVVVVVVVVVVUUUUUUUUUUU............BBBBBBBBBBBBBB.........bbb,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,",
	".......TTTTTTTTTTTTTTQQQQQQQQQQQQ,,,,,,,,,,VVVVVVVVVVV....UUUUUUU...............BBBBBBBBBBBBB...........bb,,,,,,,,bb,,,,,,,,,,,,,,,,,,,,,,",
	"......TTTTTTTTTTTTTTQQQQQQQQQQQQQQQ,,,,,,,,VVVVVVVVVV.........UU................BBBBBBBBBBBBB............bbb,,,,bbbb,,,,,,,,,,,,,,,,,,,,,,",
	".....TTTTTTTTTTTTTTTQQQQQQQQQQQQQQQQQ,,,,,VVVVVVVVVV........................L...BBBBBBBBBBBAAA.............bbbbbbbbb,,,,,,,,,,,,,,,,,,,,,,",
	".....TTTTTTTTTTTTTTTQQQQQQQQQQQQQQQQQQQ,,,VVVVVVVVVV.......................LL....BBBBBBAAAAAAA...............bbbbbbbb,,,,,,,,,,,,,,,,,,,,,",
	".....TTTTTTTTTTTTTTQQQQQQQQQQQQQQQQQQQQQQPVPPPPPPPPPP....................LLLL.....BBAAAAAAAAAAD...............bbbbbbb,,,,,,,,,,,,,,,,,,,,,",
	"......TTTTTTTTTTTTTQQQQQQQQQQQQQQQQQQQQQQPPPPPPPPPPPP....................LLLL.......AAAAAAAAAADD................bbbbb,,,,,,,,,,,,,,,,,,,,,",
	"......TTTTTTTTTTTTTQQQQQQQQQQQQQQQQQQQQQQPPPPPPPPPPPP....................LLLL........AAAAAAAADDDD................bbbbb,,,,,,,,,,,,,,,,,,,,",
	"......TTTTTTTTTTTTRQQQQQQQQQQQQQQQQQQQQQQQPPPPPPPPPP.....................LLLL.........AAAAAAACDDDDDDDD............bbbb,,,,,,YYYYY,,,,,,,,,",
	"......TTTTTTTTTTTRRRRQQQQQQQQQQQQQQQQQQQQOPPPPPPPPP.......................LL...........AAAAACCDDDDDDDD............bbbb,,,,,YYYYYYY,,,,,,,,",
	"......TTTTTTTTTTRRRRRRQQQQQQQQQQQQQQQQQQOOOPPPPPPP.........................L............AAACCCCDDDDDDDD...........bbbb,,,,YYYYYYYYY,,,,,,,",
	".......TTTTTTTTRRRRRRRRRQQQQQQQQQQQQQQQOOOOOPPPP.........................................AACCCCCDDDDDDEE..........bbbbb,,YYYYYYYYYYY,,,,,,",
	".......TTTTTTTRRRRRRRRRRRRQQQQQQQQQQQOOOOOOOOP............................KKK...............CCCCDDDDDDEEEE........bbbbb,YYYYYYYYYYYYY,,,,,",
	"......SSSSSSSRRRRRRRRRRRRRRQQQQQQQQQOOOOOOOOO..........................KKKKKK.................CCCDDDDDEEEEE.......bbbbbYYYYYYYYYYYYYY,,,,,",
	"......SSSSSSSRRRRRRRRRRRRRRRRQQQQQQOOOOOOOOO...........................KKKKKK..................CCDDDDEEEEEEEE.....bbbbbYYYYYYYYYYYYY......",
	"......SSSSSSSRRRRRRRRRRRRRRRRRRQQOOOOOOOOOO.............................KKKKKK...................CDDDEEEEEEEEE....bbaaaaYYYYYYYYYYY.......",
	".....SSSSSSSSSRRRRRRRRRRRRRRRRRROOOOOOOOOO..............................KKKKKK...................CDDEEEEEE.EEEE....aaaaaaYYYYYY..Y........",
	".....SSSSSSSSSRRRRRRRRRRRRRRRRRROOOOOOOOO...............................KKKKKK....................CDEEEEE...EEE.....aaaaaaZZZZZ...........",
	".....SSSSSSSSSRRRRRRRRRRRRRRRRRROOOOOOOOO...............................KKKKKK......................EEEE......E.....aaaaaaZZZZZ...........",
	"....SSSSSSSSSSRRRRRRRRRRRRRRRRRROOOOOOOO................................KKKKKK......................EEEE.............aaaaaaZZZZZ..........",
	"....SSSSSSSSSSSRRRRRRRRRRRRRRRRROOOOOOO.................................KKKKK........................EEEE............aaaaaaZZZZZZ.........",
	"....SSSSSSSSSSSRRRRRRRRRRRRRRRRROOOOOOOO................................KKKKK........................FFEE.............aaaaaaZZZZZ.........",
	"....SSSSSSSSSSSRRRRRRRRRRRRRRRRROOOOOOOO................................KKK.K........................FFFFE.............aaaaccZZZZ.........",
	"....SSSSSSSSSSSSRRRRRRRRRRRRRRRNNOOOOOOOO................................KK..........................FFFFF..............aacccccZ..........",
	"....SSSSSSSSSSSSRRRRRRRRRRRRRRNNNNNNNOOOO............................................................FFF................accccccee.........",
	"....SSSSSSSSSSSMMMRRRRRRRRRRRRNNNNNNNNNN............................................................FFFF.................ccccceeed........",
	".....SSSSSSSSSMMMMMRRRRRRRRRRNNNNNNNNNN...........................................................JJFFF...................cccceeeddd......",
	".....SSSSSSSSMMMMMMMMRRRRRRRNNNNNNNNNN..................................................IIIIIIJJJJJJFFF...................ccc..eeddd......",
	"......SSSSSSMMMMMMMMMMMRRRRNNNNNNNNNNN..................................................IIIIIIJJJJJ..F....................cceeeee.ddd.....",
	"......SSSSSMMMMMMMMMMMMMMRNNNNNNNNNNNN..................................................IIIIIIJJJJJ.......................cfeeeee...d.....",
	"......SSSSMMMMMMMMMMMMMMMMNNNNNNNNNN.....................................................IIIIJJJJJ........................fffffeee........",
	"......SSSMMMMMMMMMMMMMMMMMNNNNNNNNN........................................................IIJJJJJJ.......................ffffff..........",
	".....SSSMMMMMMMMMMMMMMMMMMNNNNNNNN.........................................gggg...g..........JJJJJJ........................fffff..........",
	"..............MMMMMMMMMMMMMNNNNNN....................iiii......iiiiiiiiiggggggggggg............JJJJ........................ffffff.........",
	"...............MMMMMMMMMMM.....N.................,,,,iiiiiiiiiiiiiiiiiiiiggggggggg...............JJ..........................ffff.........",
	"................MMMMMM.......................,,,,,,,,iiiiiiiiiiiiiiiiiiiiggggggggg............................................f.f.........",
	".................MMMM......................,,,,,,,iiiiiiiiiiiiiiiiiiiiiiigggggggh.........................................................",
	"..................MM..............jjjjjjjjiiiiiiiii,,,iiiiiiiiiiiiiiiiiiigghhhhhh.........................................................",
	"..................jjjjjjjjjjjjjjjjj....,,,,,,,,,,,,,,,,iiiiiiiiiiiiiiiiiihhhhhhhh.........................................................",
	".................jjjj................,,,,,,,,,,,,,,,,,,iiiiiiiiiiiiiiiiiihhhhhhhhh........................................................",
	".................jjjjj..............,,,,,,,,,,,,,,,,,,,,iiiiiiiiiiiiiiiiihhhhhhhhhh.......................................................",
	"................jjjjjjj..,,,,,....,,,,,,,,,,,,,,,,,,,,,,iiiiiiiiiiiiiiiiihhhhhhhhhh.......................................................",
	"................jjjjjjjjj,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,hhhhhhhhh........................................................",
	"................jjjjjjjj,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,hhhhhhh........................................................",
	"...............jjjjjjjj,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,hhhhh........................................................",
	"...............,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,hh.........................................................",
	"...............,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,..........................................................",
	"..............,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,..........................................................",
	".............,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,.........................................................",
	"...........,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,.......................................................",
	".........,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,.......................................................",
	"........,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,.......................................................",
	".......,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,......................................................",
]
